---
title: "Sri Lankan Water Project"
subtitle: "Survival wrt Replication 1"
author: "Vignesh Pirapaharan"
date: "May 25, 2022"
editor_options: 
  chunk_output_type: console
output:
  pdf_document: default
---

```{r load-packages}
library(tidyverse)
library(broom)
```

```{r data_cleaning, eval = FALSE}
Fish_Data_ForR_Excel_Modified_Replicate1 <- subset(Fish_Data_ForR_Excel_Modified_Replicate1,`48_surv`!= 0)
```

```{r mutating-variable, eval = FALSE}
Fish_Data_ForR_Excel_Modified_Replicate1 %>%
  mutate(Fish_Data_ForR_Excel_Modified_Replicate1, percentagesurvival = `96_surv` / Initial_total) %>%
  ggplot(aes(x = Glyphosate, y = percentagesurvival)) +
  geom_point() +
  geom_smooth(method=lm, se=FALSE) +
  labs (x = "Glyphosate concentration", y = "Percentage Survival") 
```

```{r getting_numerical_outputs_model, eval = FALSE}
Fish_Data_ForR_Excel_Modified_Replicate_New  <- Fish_Data_ForR_Excel_Modified_Replicate1 %>%
  mutate(percentagesurvival = `96_surv` / Initial_total)
model_replicate_1_survival <- lm(percentagesurvival ~ Glyphosate, data = Fish_Data_ForR_Excel_Modified_Replicate_New)
tidy(model_replicate_1_survival)
```

$$ {\widehat{Replicate1Survival}} = 0.969 - 0.00647~Glyphosate$$

```{r bar-plots_with_data, eval = FALSE}
Fish_Data_ForR_Excel_Modified_Replicate1 %>%
  group_by(`Sample Type`) %>%
  summarize(mean_percentage_survival = mean(percentagesurvival), se = sd(percentagesurvival)/sqrt(39)) %>% 
  ggplot(aes(x = `Sample Type`, y = mean_percentage_survival)) +
  geom_bar(stat = "identity") +
  geom_errorbar(aes(ymin=mean_percentage_survival-se, ymax=mean_percentage_survival+se))
```
